/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.IoT.Operations.Mock.AdrBaseService
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.IoT.Operations.Mock;

    /// <summary>
    /// A reference to the Device and Endpoint within the device (connection information) used by brokers to connect that provides data points for this asset.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class AssetDeviceRef : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// Name of the device resource.
        /// </summary>
        [JsonPropertyName("deviceName")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public string DeviceName { get; set; } = default!;

        /// <summary>
        /// The name of endpoint to use.
        /// </summary>
        [JsonPropertyName("endpointName")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public string EndpointName { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (DeviceName is null)
            {
                throw new ArgumentNullException("deviceName field cannot be null");
            }
            if (EndpointName is null)
            {
                throw new ArgumentNullException("endpointName field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (DeviceName is null)
            {
                throw new ArgumentNullException("deviceName field cannot be null");
            }
            if (EndpointName is null)
            {
                throw new ArgumentNullException("endpointName field cannot be null");
            }
        }
    }
}
