/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.IoT.Operations.Mock.AdrBaseService
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.IoT.Operations.Mock;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class CreateOrUpdateDiscoveredAssetRequestSchema : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// The 'discoveredAsset' Field.
        /// </summary>
        [JsonPropertyName("discoveredAsset")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public DiscoveredAsset DiscoveredAsset { get; set; } = default!;

        /// <summary>
        /// The 'discoveredAssetName' Field.
        /// </summary>
        [JsonPropertyName("discoveredAssetName")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public string DiscoveredAssetName { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (DiscoveredAsset is null)
            {
                throw new ArgumentNullException("discoveredAsset field cannot be null");
            }
            if (DiscoveredAssetName is null)
            {
                throw new ArgumentNullException("discoveredAssetName field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (DiscoveredAsset is null)
            {
                throw new ArgumentNullException("discoveredAsset field cannot be null");
            }
            if (DiscoveredAssetName is null)
            {
                throw new ArgumentNullException("discoveredAssetName field cannot be null");
            }
        }
    }
}
