/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.IoT.Operations.Mock.AdrBaseService
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.IoT.Operations.Mock;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class DetailsSchemaElementSchema
    {
        /// <summary>
        /// Multi-part error code for classification and root causing of errors (ex: 400.200.100.432).
        /// </summary>
        [JsonPropertyName("code")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string? Code { get; set; } = default;

        /// <summary>
        /// Unique identifier for the transaction to aid in debugging.
        /// </summary>
        [JsonPropertyName("correlationId")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string? CorrelationId { get; set; } = default;

        /// <summary>
        /// Human readable helpful detailed text context for debugging (ex: “The following mechanisms are supported...”).
        /// </summary>
        [JsonPropertyName("info")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string? Info { get; set; } = default;

        /// <summary>
        /// Human readable helpful error message to provide additional context for error (ex: “Authentication method not supported”).
        /// </summary>
        [JsonPropertyName("message")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string? Message { get; set; } = default;

    }
}
