/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.IoT.Operations.Mock.AdrBaseService
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.IoT.Operations.Mock;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class GetAssetStatusResponsePayload : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// The Command response argument.
        /// </summary>
        [JsonPropertyName("assetStatus")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public AssetStatus AssetStatus { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (AssetStatus is null)
            {
                throw new ArgumentNullException("assetStatus field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (AssetStatus is null)
            {
                throw new ArgumentNullException("assetStatus field cannot be null");
            }
        }
    }
}
