/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.IoT.Operations.Mock.AdrBaseService
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.IoT.Operations.Mock;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class GetAssetStatusResponseSchema
    {
        /// <summary>
        /// The 'assetStatus' Field.
        /// </summary>
        [JsonPropertyName("assetStatus")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public AssetStatus? AssetStatus { get; set; } = default;

        /// <summary>
        /// The 'getAssetStatusError' Field.
        /// </summary>
        [JsonPropertyName("getAssetStatusError")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public AkriServiceError? GetAssetStatusError { get; set; } = default;

    }
}
