/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.IoT.Operations.Mock.AdrBaseService
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.IoT.Operations.Mock;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class SetNotificationPreferenceForAssetUpdatesRequestSchema : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// The 'assetName' Field.
        /// </summary>
        [JsonPropertyName("assetName")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public string AssetName { get; set; } = default!;

        /// <summary>
        /// The 'notificationPreference' Field.
        /// </summary>
        [JsonPropertyName("notificationPreference")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public NotificationPreference NotificationPreference { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (AssetName is null)
            {
                throw new ArgumentNullException("assetName field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (AssetName is null)
            {
                throw new ArgumentNullException("assetName field cannot be null");
            }
        }
    }
}
