/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.IoT.Operations.Mock.AdrBaseService
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.IoT.Operations.Mock;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class SetNotificationPreferenceForAssetUpdatesResponseSchema
    {
        /// <summary>
        /// The 'responsePayload' Field.
        /// </summary>
        [JsonPropertyName("responsePayload")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string? ResponsePayload { get; set; } = default;

        /// <summary>
        /// The 'setNotificationPreferenceForAssetUpdatesError' Field.
        /// </summary>
        [JsonPropertyName("setNotificationPreferenceForAssetUpdatesError")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public AkriServiceError? SetNotificationPreferenceForAssetUpdatesError { get; set; } = default;

    }
}
