/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.IoT.Operations.Mock.AdrBaseService
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml;
    using Azure.Iot.Operations.Protocol;
    using Azure.Iot.Operations.Protocol.RPC;
    using Azure.Iot.Operations.Protocol.Models;
    using Azure.IoT.Operations.Mock;

    public static partial class AdrBaseService
    {
        /// <summary>
        /// Specializes a <c>CommandExecutor</c> class for Command 'setNotificationPreferenceForAssetUpdates'.
        /// </summary>
        public class SetNotificationPreferenceForAssetUpdatesCommandExecutor : CommandExecutor<SetNotificationPreferenceForAssetUpdatesRequestPayload, SetNotificationPreferenceForAssetUpdatesResponseSchema>
        {
            /// <summary>
            /// Initializes a new instance of the <see cref="SetNotificationPreferenceForAssetUpdatesCommandExecutor"/> class.
            /// </summary>
            public SetNotificationPreferenceForAssetUpdatesCommandExecutor(ApplicationContext applicationContext, IMqttPubSubClient mqttClient)
                : base(applicationContext, mqttClient, "setNotificationPreferenceForAssetUpdates", new Utf8JsonSerializer())
            {
                TopicTokenMap["modelId"] = "dtmi:com:microsoft:akri:AdrBaseService;1";
                if (mqttClient.ClientId != null)
                {
                    TopicTokenMap["executorId"] = mqttClient.ClientId;
                }
                TopicTokenMap["commandName"] = "setNotificationPreferenceForAssetUpdates";
            }
        }
    }
}
