/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.IoT.Operations.Mock.AdrBaseService
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.IoT.Operations.Mock;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class UpdateDeviceStatusResponseSchema
    {
        /// <summary>
        /// The 'updatedDeviceStatus' Field.
        /// </summary>
        [JsonPropertyName("updatedDeviceStatus")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public DeviceStatus? UpdatedDeviceStatus { get; set; } = default;

        /// <summary>
        /// The 'updateDeviceStatusError' Field.
        /// </summary>
        [JsonPropertyName("updateDeviceStatusError")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public AkriServiceError? UpdateDeviceStatusError { get; set; } = default;

    }
}
