/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.IoT.Operations.Mock.AdrBaseService
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.IoT.Operations.Mock;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class UpdateAssetStatusResponseSchema
    {
        /// <summary>
        /// The 'updateAssetStatusError' Field.
        /// </summary>
        [JsonPropertyName("updateAssetStatusError")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public AkriServiceError? UpdateAssetStatusError { get; set; } = default;

        /// <summary>
        /// The 'updatedAssetStatus' Field.
        /// </summary>
        [JsonPropertyName("updatedAssetStatus")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public AssetStatus? UpdatedAssetStatus { get; set; } = default;

    }
}
