/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.IoT.Operations.Mock.AdrBaseService
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.IoT.Operations.Mock;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class X509credentialsSchema : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// The name of the secret containing the certificate and private key (e.g. stored as .der/.pem or .der/.pfx).
        /// </summary>
        [JsonPropertyName("certificateSecretName")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public string CertificateSecretName { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (CertificateSecretName is null)
            {
                throw new ArgumentNullException("certificateSecretName field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (CertificateSecretName is null)
            {
                throw new ArgumentNullException("certificateSecretName field cannot be null");
            }
        }
    }
}
