// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

namespace Azure.IoT.Operations.Mock
{
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CA1515 // Consider making public types internal
    public class EmptyJson
#pragma warning restore CA1515 // Consider making public types internal
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
    {
    }
}
