/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.IoT.Operations.Mock.DeviceDiscoveryService
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.IoT.Operations.Mock;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class CreateOrUpdateDiscoveredDeviceResponseSchema
    {
        /// <summary>
        /// The 'createOrUpdateDiscoveredDeviceError' Field.
        /// </summary>
        [JsonPropertyName("createOrUpdateDiscoveredDeviceError")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public AkriServiceError? CreateOrUpdateDiscoveredDeviceError { get; set; } = default;

        /// <summary>
        /// The 'discoveredDeviceResponse' Field.
        /// </summary>
        [JsonPropertyName("discoveredDeviceResponse")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public DiscoveredDeviceResponseSchema? DiscoveredDeviceResponse { get; set; } = default;

    }
}
