/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.IoT.Operations.Mock.DeviceDiscoveryService
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml;
    using Azure.Iot.Operations.Protocol;
    using Azure.Iot.Operations.Protocol.RPC;
    using Azure.Iot.Operations.Protocol.Models;
    using Azure.IoT.Operations.Mock;

    public static partial class DeviceDiscoveryService
    {
        /// <summary>
        /// Specializes a <c>CommandExecutor</c> class for Command 'createOrUpdateDiscoveredDevice'.
        /// </summary>
        public class CreateOrUpdateDiscoveredDeviceCommandExecutor : CommandExecutor<CreateOrUpdateDiscoveredDeviceRequestPayload, CreateOrUpdateDiscoveredDeviceResponseSchema>
        {
            /// <summary>
            /// Initializes a new instance of the <see cref="CreateOrUpdateDiscoveredDeviceCommandExecutor"/> class.
            /// </summary>
            public CreateOrUpdateDiscoveredDeviceCommandExecutor(ApplicationContext applicationContext, IMqttPubSubClient mqttClient)
                : base(applicationContext, mqttClient, "createOrUpdateDiscoveredDevice", new Utf8JsonSerializer())
            {
                TopicTokenMap["modelId"] = "dtmi:com:microsoft:akri:DeviceDiscoveryService;1";
                if (mqttClient.ClientId != null)
                {
                    TopicTokenMap["executorId"] = mqttClient.ClientId;
                }
                TopicTokenMap["commandName"] = "createOrUpdateDiscoveredDevice";
            }
        }
    }
}
