/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.IoT.Operations.Mock.DeviceDiscoveryService
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.IoT.Operations.Mock;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class DiscoveredDeviceOutboundEndpointsSchema : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// The 'assigned' Field.
        /// </summary>
        [JsonPropertyName("assigned")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public Dictionary<string, DeviceOutboundEndpoint> Assigned { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (Assigned is null)
            {
                throw new ArgumentNullException("assigned field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (Assigned is null)
            {
                throw new ArgumentNullException("assigned field cannot be null");
            }
        }
    }
}
