/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.IoT.Operations.Mock.DeviceDiscoveryService
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.IoT.Operations.Mock;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class DiscoveredDeviceEndpoints
    {
        /// <summary>
        /// The 'inbound' Field.
        /// </summary>
        [JsonPropertyName("inbound")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public Dictionary<string, DiscoveredDeviceInboundEndpointSchema>? Inbound { get; set; } = default;

        /// <summary>
        /// The 'outbound' Field.
        /// </summary>
        [JsonPropertyName("outbound")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public DiscoveredDeviceOutboundEndpointsSchema? Outbound { get; set; } = default;

    }
}
